<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class BookSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $books = [
            [
                'title' => 'Sejarah Cina',
                'author' => 'Frederick Wells W.',
                'description' => '',
                'cover_path' => 'a history of china.jpg',
                'category_id' => 8,
            ],
            [
                'title' => 'Agrobisnis Budidaya Lidah Buaya',
                'author' => 'Tim Agro Mandiri',
                'description' => '',
                'cover_path' => 'agrobisnis budidaya lidah buaya.jpg',
                'category_id' => 3,
            ],
            [
                'title' => 'Agrobisnis Budidaya Lidah Buaya',
                'author' => 'Tim Agro Mandiri',
                'description' => '',
                'cover_path' => 'agrobisnis budidaya lidah buaya.jpg',
                'category_id' => 3,
            ],
            [
                'title' => 'Aku Bisa Jika Aku Berpikir Bisa',
                'author' => 'Feri Tjahjono',
                'description' => '',
                'cover_path' => 'aku bisa jika aku berpikir biasa.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Aku Memilih Bahagia',
                'author' => 'Fery Tjahjono',
                'description' => '',
                'cover_path' => 'aku memilih bahagia',
                'category_id' => 6,
            ],
            [
                'title' => 'Anggrek Bayi Tidur',
                'author' => 'Sri Widawati',
                'description' => '',
                'cover_path' => 'anggrek bayi tidur.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Bekerja dengan Cinta',
                'author' => 'John Afifi',
                'description' => '',
                'cover_path' => 'bekerja dengan cinta .jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Belajar Menuang Ide dalam Puisi, Cerita, Drama',
                'author' => 'Wendi Widya Ratna Dewi',
                'description' => '',
                'cover_path' => 'belajar menuang ide dalam puisi cerita drama.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Bencana di Lingkungan',
                'author' => 'Pakar Raya Pustaka',
                'description' => '',
                'cover_path' => 'bencana di lingkungan.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Berdisiplin',
                'author' => 'Sukini',
                'description' => '',
                'cover_path' => 'berdisiplin.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Bertanam Kentang',
                'author' => 'Ir. Widi Agustin, M.P.',
                'description' => '',
                'cover_path' => 'bertanam kentang.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Cara Budidaya Lebah Madu yang Berhasil',
                'author' => 'Tim Agro Mandiri',
                'description' => '',
                'cover_path' => 'cara budidaya lebah madu yang berhasil.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Cara Cerdas Budidaya Kakao',
                'author' => 'Ahmad Fanani',
                'description' => '',
                'cover_path' => 'cara cerdas budidaya kakao.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Cara Memperbaiki Alat-Alat Rumah Tangga',
                'author' => 'Ir. PM Aritonang',
                'description' => '',
                'cover_path' => 'cara memperbaiki alat alat rumah tanga .jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Cara Merakit Aquarium',
                'author' => 'Drs. Achdi Achmadi',
                'description' => '',
                'cover_path' => 'cara merakit aquarium.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Cerita Terbaik Pembentuk Budi Pekerti',
                'author' => 'siti anisah',
                'description' => '',
                'cover_path' => 'cerita terbaik pembentuk budi pekerti seri pendidikan karakter.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Dasar-dasar Berenang',
                'author' => 'Dewi Nawangsari',
                'description' => '',
                'cover_path' => 'dasar dasar berenang.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Dasar-dasar Keperawatan',
                'author' => 'Tim Media Cipta Guru SMK',
                'description' => '',
                'cover_path' => 'dasar dasar keperawatan.jpg',
                'category_id' => 4,
            ],
            [
                'title' => 'Dasar-dasar Budidaya Perikanan',
                'author' => 'Tim Media Cipta Guru SMK',
                'description' => '',
                'cover_path' => 'dasar-dasar budi daya perikanan.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Demokrasi',
                'author' => 'Panjalu Wiranggani',
                'description' => '',
                'cover_path' => 'demokrasi.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Dimana Ada Kemauan Disana Ada Kemudahan',
                'author' => 'Feri Tjahjono',
                'description' => '',
                'cover_path' => 'dimana ada kemauan di sana ada kemudahan.jpg',
                'category_id' => 3,
            ],
            [
                'title' => 'Eksperimen Sains',
                'author' => 'Nini Subini, S.Pd',
                'description' => '',
                'cover_path' => 'eksperimen sains.jpg',
                'category_id' => 2,
            ],
            [
                'title' => 'Elektronik di Rumah Kita',
                'author' => 'Hadi Karyanto, S.P.',
                'description' => '',
                'cover_path' => 'elektronik di rumah kita.jpg',
                'category_id' => 1,
            ],
            [
                'title' => 'Ensiklopedi Hindu',
                'author' => 'Penerbit Paramita Surabaya',
                'description' => '',
                'cover_path' => 'ensiklopedi hindu.jpg',
                'category_id' => 11,
            ],
            [
                'title' => 'Ensiklopedia Anak Nusantara',
                'author' => 'Tim Afin and Friends',
                'description' => '',
                'cover_path' => 'ensklopedia anak nusantara.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Every Man is a King',
                'author' => 'Orison Swett Marden',
                'description' => '',
                'cover_path' => 'every man a king.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Gagal Bukan Berarti Sia-sia',
                'author' => 'Teo Sutan',
                'description' => '',
                'cover_path' => 'gagal bukan berarti sia-sia.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Gaguritan Sutasoma 1, jilid 1',
                'author' => 'Mangku Pande Gd. Rauh Artana',
                'description' => '',
                'cover_path' => 'gaguritan gaguritan sutasoma I jilid I.jpg',
                'category_id' => 11,
            ],
            [
                'title' => 'Gaguritan Watugangga',
                'author' => 'Jro Made M.Mardika',
                'description' => '',
                'cover_path' => 'gaguritan watugangga.jpg',
                'category_id' => 11,
            ],
            [
                'title' => 'Gajah Mada, Taktha dan Angkara',
                'author' => 'Langit Kresna Hariadi',
                'description' => '',
                'cover_path' => 'gajah mada takhta dan angkara.jpg',
                'category_id' => 8,
            ],
            [
                'title' => 'Gambar Teknik Manufaktur Pembelajaran SMK',
                'author' => 'Tim Media Cipta Guru SMK',
                'description' => '',
                'cover_path' => 'gambar teknik menufaktur pemebelajaran smk.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Hama dan Penyakit Tanaman Pangan',
                'author' => 'Ir. Sartono Joko S., MP',
                'description' => '',
                'cover_path' => 'Hama dan Penyakit Tanaman Pangan.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Hamsad Rangkut Cemara',
                'author' => '-',
                'description' => '',
                'cover_path' => 'hamsad rangkuti cemara.jpg',
                'category_id' => 10,
            ],
            [
                'title' => 'Hari Raya & Kakawin Siwaratri Kalpa',
                'author' => 'I.B, Suparta Ardhana',
                'description' => '',
                'cover_path' => 'hari raya dan kakawin siwaratri kalpa.jpg',
                'category_id' => 11,
            ],
            [
                'title' => 'Hidroponik Teknologi Budidaya Tanaman Tanpa Tanah',
                'author' => 'Tim Agro Mandiri',
                'description' => '',
                'cover_path' => 'hidroponik teknologi budidaya tanaman tanpa tanah.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Hidup Sehat, Kinejra Melejit',
                'author' => 'Heru Setyaka',
                'description' => '',
                'cover_path' => 'hidup sehat kinerja melejit.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'I Love You',
                'author' => 'Wilda Ayu Mandasari Baskoro',
                'description' => '',
                'cover_path' => 'hidup sehat kinerja melejit.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Ibu Tien dan Pak Harto',
                'author' => 'Ira Tri Onggo',
                'description' => '',
                'cover_path' => 'ibu tien dan pak harto.jpg',
                'category_id' => 10,
            ],
            [
                'title' => 'Step by Step Budidaya Ikan Hias Cupang',
                'author' => 'Devan Ramadhan',
                'description' => '',
                'cover_path' => 'ikan hias cupang.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Ilmu Lengkap Bahan Makanan',
                'author' => 'Tim Bina Karya SMK',
                'description' => '',
                'cover_path' => 'ilmu lengka bahan makanan (pemilihan, penyimpanan, pengelohan).jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Ilmu Seni Rupa Dasar',
                'author' => 'Tim Bina Karya SMK',
                'description' => '',
                'cover_path' => 'ilmu seni rupa dasar.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Jadilah Pemimpin Idaman',
                'author' => 'Mahawira Abimayu',
                'description' => '',
                'cover_path' => 'jadilah pemimpin idaman.jpg',
                'category_id' => 6,
            ],
            [
                'title' => 'Jamu Ramuan surga Plus Pijat Refleksi',
                'author' => 'Jarwo Pramono',
                'description' => '',
                'cover_path' => 'jamu ramuan surga pijat refleksi.jpg',
                'category_id' => 4,
            ],
            [
                'title' => 'Jenis-jenis Banten Tebasan',
                'author' => 'Drs. I Wayan Dunia',
                'description' => '',
                'cover_path' => 'jenis banten tebasan.jpg',
                'category_id' => 11,
            ],
            [
                'title' => 'Geguritan Jnana Siddhi (Sarining Kasuksman)',
                'author' => 'Drs. I Wayan Mudayasa, S.H.,M.H',
                'description' => '',
                'cover_path' => 'jnana sidhi.jpg',
                'category_id' => 11,
            ],
            [
                'title' => 'Jus Ampuh Penumpas Aneka Penyakit',
                'author' => 'Mama Lubna',
                'description' => '',
                'cover_path' => 'jus ampuh penumpas aneka penyakit berat.jpg',
                'category_id' => 4,
            ],
            [
                'title' => 'Kampungku Dikepung Sayuran',
                'author' => 'Nasin El-Kabumaini, DKK.',
                'description' => '',
                'cover_path' => 'kampungku dikepung sayuran.jpg',
                'category_id' => 4,
            ],
            [
                'title' => 'Kamus Bahasa Bali',
                'author' => 'Wayan Budha Gautama',
                'description' => '',
                'cover_path' => 'kamus bahasa bali.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Kamus Istilah Boga',
                'author' => 'Daru Wijayanti',
                'description' => '',
                'cover_path' => 'kamus istilah boga.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Kamus Istilah Sains & Teknologi',
                'author' => 'Mohammad Sholihul Wafi',
                'description' => '',
                'cover_path' => 'kamus istilah sains dan teknologi.jpg',
                'category_id' => 5,
            ],
            [
                'title' => 'Kamus Istilah Sejarah & Budaya',
                'author' => 'Alvi Merlina',
                'description' => '',
                'cover_path' => 'kamus istilah sejarah dan budidaya.jpg',
                'category_id' => 5,
            ],

        ];

        foreach ($books as $index => $book) {
            DB::table('books')->insert([
                'title' => $book['title'],
                'author' => $book['author'],
                'description' => $book['description'],
                'cover_path' => $book['cover_path'],
                'category_id' => $book['category_id'],
                'created_at' => Carbon::now()->subDays($index * 3),
                'updated_at' => null,
            ]);
        }
    }
}
